apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  labels:
    sample: horizontalpodautoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      sample: horizontalpodautoscaler
      layer: backend
  template:
    metadata:
      labels:
        sample: horizontalpodautoscaler
        layer: backend
    spec:
      containers:
        - name: c1
          image: rajchaudhuri/ldgen:0.1.0
          resources:
            requests:
              cpu: 0.2
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    sample: horizontalpodautoscaler
spec:
  type: NodePort
  selector:
    sample: horizontalpodautoscaler
    layer: backend
  ports:
    - name: web
      port: 8080
      nodePort: 31000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-dep-scaler
  labels:
    sample: horizontalpodautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-dep
  targetCPUUtilizationPercentage: 50
  maxReplicas: 6
  minReplicas: 1