version: "3"

networks:
  dbnet:

volumes:
   db1vol:

services:
  backend:
    image: mysql
    volumes:
      - db1vol:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_ROOT_PASSWORD=something

  frontend:
    image: adminer
    networks:
      - dbnet
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=backend
